version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.12.0
      
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: "Pull solc 0.4.23 docker image"
          command: docker pull ethereum/solc:0.4.23

      - run:
          name: "Pull solc 0.4.24 docker image"
          command: docker pull ethereum/solc:0.4.24

      - run:
          name: "Init submodules"
          command: git submodule update --recursive --init

      - restore_cache:
          keys:
            - v2-colonyNetwork-dependencies-{{ checksum "packages/kyodo-contracts/lib/colonyNetwork/yarn.lock" }}

      - run:
          name: "yarn install colonyNetwork"
          command: (cd packages/kyodo-contracts/lib/colonyNetwork && yarn install --pure-lockfile --network-concurrency 1)

      - run:
          name: "yarn run provision token contracts"
          command: (cd packages/kyodo-contracts/lib/colonyNetwork && yarn run provision:token:contracts)

      - save_cache:
          paths:
            - packages/kyodo-contracts/lib/colonyNetwork/node_modules
          key: v2-colonyNetwork-dependencies-{{ checksum "packages/kyodo-contracts/lib/colonyNetwork/yarn.lock" }}

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: "Install Dependencies"
          command: yarn install --pure-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: "Install lsof"
          command: |
            sudo apt-get update
            sudo apt-get install lsof

      - run:
          name: "Start Ganache"
          command: yarn start-ganache
          background: true

      - run:
          name: "Deploy Contracts"
          command: yarn deploy-contracts

      - run:
          name: "Test Packages"
          command: yarn test
