export const BASE_CURRENCY = 'EUR';

export const LOAD_RATE_REQUEST = 'LOAD_RATE_REQUEST';
export const LOAD_RATE_SUCCESS = 'LOAD_RATE_SUCCESS';
export const LOAD_MULTISIG_BALANCE_REQUEST = 'LOAD_MULTISIG_BALANCE_REQUEST';
export const LOAD_MULTISIG_BALANCE_SUCCESS = 'LOAD_MULTISIG_BALANCE_SUCCESS';
export const LOAD_HISTORICAL_RATES_REQUEST = 'LOAD_HISTORICAL_RATES_REQUEST';
export const LOAD_HISTORICAL_RATES_SUCCESS = 'LOAD_HISTORICAL_RATES_SUCCESS';
export const LOAD_PERIOD_TASKS_REQUEST = 'LOAD_PERIOD_TASKS_REQUEST';
export const LOAD_PERIOD_TASKS_SUCCESS = 'LOAD_PERIOD_TASKS_SUCCESS';
export const LOAD_CURRENT_PERIOD_INFO_REQUEST =
  'LOAD_CURRENT_PERIOD_INFO_REQUEST';
export const LOAD_CURRENT_PERIOD_INFO_SUCCESS =
  'LOAD_CURRENT_PERIOD_INFO_SUCCESS';
export const GET_COLONY_NETWORK_CLIENT_REQUEST =
  'GET_COLONY_NETWORK_CLIENT_REQUEST';
export const GET_COLONY_NETWORK_CLIENT_SUCCESS =
  'GET_COLONY_NETWORK_CLIENT_SUCCESS';
export const GET_COLONY_REQUEST = 'GET_COLONY_REQUEST';
export const GET_COLONY_SUCCESS = 'GET_COLONY_SUCCESS';
export const GET_POT_BALANCE_REQUEST = 'GET_POT_BALANCE_REQUEST';
export const GET_POT_BALANCE_SUCCESS = 'GET_POT_BALANCE_SUCCESS';
export const GET_DOMAINS_BALANCES_REQUEST = 'GET_DOMAINS_BALANCES_REQUEST';
export const GET_DOMAINS_BALANCES_SUCCESS = 'GET_DOMAINS_BALANCES_SUCCESS';
export const GET_DOMAINS_REQUEST = 'GET_DOMAINS_REQUEST';
export const GET_DOMAINS_SUCCESS = 'GET_DOMAINS_SUCCESS';
