export const BASE_CURRENCY = 'EUR';

export const LOAD_RATE_REQUEST = 'LOAD_RATE_REQUEST';
export const LOAD_RATE_SUCCESS = 'LOAD_RATE_SUCCESS';
export const LOAD_MULTISIG_BALANCE_REQUEST = 'LOAD_MULTISIG_BALANCE_REQUEST';
export const LOAD_MULTISIG_BALANCE_SUCCESS = 'LOAD_MULTISIG_BALANCE_SUCCESS';
export const LOAD_HISTORICAL_RATES_REQUEST = 'LOAD_HISTORICAL_RATES_REQUEST';
export const LOAD_HISTORICAL_RATES_SUCCESS = 'LOAD_HISTORICAL_RATES_SUCCESS';
export const LOAD_PERIOD_TASKS_REQUEST = 'LOAD_PERIOD_TASKS_REQUEST';
export const LOAD_PERIOD_TASKS_SUCCESS = 'LOAD_PERIOD_TASKS_SUCCESS';
