export const BASE_CURRENCY = 'EUR';

export const LOAD_RATE_REQUEST = 'LOAD_RATE_REQUEST';
export const LOAD_RATE_SUCCESS = 'LOAD_RATE_SUCCESS';
export const LOAD_MULTISIG_BALANCE_REQUEST = 'LOAD_MULTISIG_BALANCE_REQUEST';
export const LOAD_MULTISIG_BALANCE_SUCCESS = 'LOAD_MULTISIG_BALANCE_SUCCESS';
